### ISSUE TITLE
Explanatory copy

### ISSUE THREAD

**Issue by meghanhade** [mapzen/mobility-explorer#327]
Copy will link to map-matching docs.

**Comment by rmglennon** [comment]
Some potential UI text. I can update this in the source (if you get me set up) or we can sit down together to see how it looks.

Main heading: TRY MAP MATCHING (good enough!)

Paragraph at the top of the section (on two lines, like isochrones):
Match GPS locations to a known route and see detailed attributes about the line. <br>
Read more about map matching`*`, or get started by choosing a sample GPX file or uploading your own.
`*` where the link goes to https://mapzen.com/documentation/mobility/explorer/map-matching/ (this page is not there yet)

Heading above the drop-down for Sample GPX trace --> Choose a GPX trace

Drop-down list text for Select a sample GPX trace... --> either no text or default to the first entry in the list. I think it's preferred to put the verb on the heading, rather than the drop-down list.

Button for See the map-match for this trace --> Match this GPX (I thought saying trace in there might be confusing because trace can also be a verb.

See the route segment info by --> Style lines by:
* Grade 
* Speed limit
^ Sentence case capitalization on radio buttons
Style lines by: is matches the text in the other sections

? for the grade and speed limit section: Display each matched line segment by either its slope or speed limit, if known. Click a segment on the map to see detailed attributes.

intro heading for table: Attributes of the selected segment 

? for table: View attribute information for the segment you clicked on the map. Values are from OpenStreetMap source data and Mapzen Mobility routing calculations.
